#!/usr/bin/env node
// Packs models/*.glb into js/models-data.js as base64 (G.MODELS).
'use strict';
var fs = require('fs'), path = require('path');
var dir = path.join(__dirname, '..', 'models');
var out = {};
fs.readdirSync(dir).filter(function (f) { return f.endsWith('.glb'); }).forEach(function (f) {
  out[f.replace('.glb', '')] = fs.readFileSync(path.join(dir, f)).toString('base64');
});
var js = '/* GENERATED by tools/pack-models.js — Blender-authored set pieces (base64 GLB). */\n' +
  '(function () { window.G = window.G || {}; window.G.MODELS = ' + JSON.stringify(out) + '; })();\n';
fs.writeFileSync(path.join(__dirname, '..', 'js', 'models-data.js'), js);
console.log('packed', Object.keys(out).join(', '),
  '->', (js.length / 1024).toFixed(0) + 'KB');
